window.CITYDRIVE_SEED_RESTAURANTS = [
  { name: 'Е36 (ONESHOTT COFFEE kitchen)', link: 'https://go.2gis.com/oYTbJ' },
  { name: 'САРЫАРКА ( Saryarqa)', link: 'https://go.2gis.com/VXOxM' },
  { name: 'КЕНЕСАРЫ ( French Cafe )', link: 'https://go.2gis.com/b9SWn' },
  { name: 'КЖ ( French Cafe au Parc )', link: 'https://go.2gis.com/vrSq3' },
  { name: 'РИРИ ( Riri )', link: 'https://go.2gis.com/dlsVp' },
  { name: 'НУР (WEDRINK)', link: 'https://go.2gis.com/qEOnY' },
  { name: 'КС (WEDRINK)', link: 'https://go.2gis.com/h9FSf' },
  { name: 'ОТТАМАН (OTTAMAN)', link: 'https://go.2gis.com/XCJoj' },
  { name: 'ХШ (EXPRESSO CLASSIC)', link: 'https://go.2gis.com/1xXj1' },
  { name: 'АБУ (MARMELADE)', link: 'https://go.2gis.com/qUseb' },
  { name: 'САРАЙШИК (FUNTOWN)', link: 'https://go.2gis.com/yJzCf' },
  { name: 'РУТС (ROOTS)', link: 'https://go.2gis.com/LJigE' },
  { name: 'ТӨР (ТӨР)', link: 'https://2gis.kz/astana/firm/70000001019651813?m=71.459492%2C51.128814%2F16' },
  { name: 'АБАЯ (SUSHI FOX)', link: 'https://2gis.kz/astana/firm/70000001055336448?m=71.41247%2C51.166932%2F16' },
  { name: 'ТАГАМ Конаев (TAGAM)', link: 'https://go.2gis.com/8TAXZ' },
  { name: 'МОРИС (CAFE MORIRS)', link: 'https://go.2gis.com/xeFvz' },
  { name: 'МЕГА (Донер на углях)', link: 'https://go.2gis.com/IkVfd' },
  { name: 'РЕСПА (COFFE BOOM)', link: 'https://go.2gis.com/6zeWm' },
  { name: 'БОКЕЙХАНА (COFFE BOOM)', link: 'https://2gis.kz/astana/inside/70030076193996397/firm/70000001088141385?m=71.428224%2C51.086588%2F16' },
  { name: 'ТОЛЕ БИ ( ONESHOTT COFFEE kitchen  )', link: 'https://go.2gis.com/P5OET' },
  { name: 'ББР (BOOM BOOM ROOM)', link: 'https://go.2gis.com/dGqhR' },
  { name: 'АЗИЯ (COFFE BOOM)', link: 'https://go.2gis.com/l27dK' },
  { name: 'ЛОНДОН (LONDON)', link: 'https://go.2gis.com/wIgaJ' },
  { name: 'T28 (CHEZ GEORGES)', link: 'https://go.2gis.com/iCdmi' },
  { name: 'Кальби (Kalbi)', link: 'https://go.2gis.com/CrszA' },
  { name: 'ЖТ (ЖУМСАК ТАГАМ)', link: 'https://go.2gis.com/lyPVN' },
  { name: 'М1 (МАНГАЛ МОМЫШУЛЫ)', link: 'https://go.2gis.com/avFHs' },
  { name: 'М2 (МАНГАЛ БОКЕЙХАНА)', link: 'https://go.2gis.com/qlFRa' },
  { name: 'АСАТУ (АСАТУ)', link: 'https://go.2gis.com/m2x6J' },
  { name: 'ФИШ ( Fish Fried  )', link: 'https://go.2gis.com/vUQ3v' },
  { name: 'САЗАН (SAZAN FISH)', link: 'https://go.2gis.com/SrBSb' },
  { name: 'ТАО ТАО (TAO TAO)', link: 'https://go.2gis.com/q3LXd' },
  { name: 'АФРА (AFRA)', link: 'https://go.2gis.com/NhTbX' },
  { name: 'АУРА ( Aura Verdant)', link: 'https://go.2gis.com/xTDqe' },
  { name: 'РУМИ (RUMI)', link: 'https://go.2gis.com/HMXv3' },
  { name: 'ПИРО (PIRO)', link: 'https://go.2gis.com/JLZ5h' },
  { name: 'Н СИТИ ( Bella Ciao  )', link: 'https://go.2gis.com/HD0bv' },
  { name: 'ШАТЕ ( Shate  )', link: 'https://go.2gis.com/tA37E' },
  { name: 'ИЗМИР (ИЗМИР)', link: 'https://go.2gis.com/mIwGv' },
  { name: 'БУДДА ( Buddha-Bar Astana )', link: 'https://go.2gis.com/F4smM' },
  { name: 'ПРОВИНО ( Provino Wine Bar&Store )', link: 'https://go.2gis.com/OtjN7' },
  { name: 'КОНГРЕСС (  Provino Wine Bar&Store   )', link: 'https://go.2gis.com/RIzAw' },
  { name: 'ДО ВИНЧИ ( Code Da Vinci   )', link: 'https://go.2gis.com/A165S' },
  { name: 'ТАТТЫ ( Qatty tatty   )', link: 'https://go.2gis.com/38HKf' },
  { name: 'Тайм ( SushiTimeAstana.kz )', link: 'https://2gis.kz/astana/firm/70000001104314350?m=71.418063%2C51.134657%2F16' },
  { name: 'ЯСУДА (YASUDA SUSHI)', link: 'https://go.2gis.com/nV9id' },
  { name: 'Гурьев ( Гурьев)', link: 'https://go.2gis.com/YNKRI' },
  { name: 'КАМАЛ (ГУРЬЕВ 2)', link: 'https://go.2gis.com/prvFk' },
  { name: 'ТАЙО ( Taiyo )', link: 'https://go.2gis.com/OgQDJ' },
  { name: 'ЭКСПО (МЯТНЫЙ ЭКСПО)', link: 'https://go.2gis.com/qKqXa' },
  { name: 'ЦЕХ ( ONESHOTT COFFEE kitchen)', link: 'https://go.2gis.com/yWXb0' },
  { name: '13 бар (Mirage)', link: 'https://go.2gis.com/v6OqX' },
  { name: 'Углях1 (The Doner на углях)', link: 'https://go.2gis.com/Du8gT' },
  { name: 'Уголях 3 (The Doner на углях)', link: 'https://go.2gis.com/qoKUc' },
  { name: 'Вудли (Woodly)', link: 'https://go.2gis.com/KF4Zv' },
  { name: 'Кофе пик (Peak buro)', link: 'https://go.2gis.com/G5gU1' },
  { name: 'Плаза (ONESHOTT COFFEE kitchen)', link: 'https://go.2gis.com/YBhzB' },
  { name: 'Мастер 1   (Master Coffee)', link: 'https://go.2gis.com/vAOPj' },
  { name: 'Жетису (Zhety Su Банный комплекс)', link: 'https://go.2gis.com/GiZF9' },
  { name: 'Гол 1 (Гол+Пас )', link: 'https://go.2gis.com/8U5B5' },
  { name: 'Гол-2 (Гол+Пас)', link: 'https://go.2gis.com/ImC5b' },
  { name: 'Точка ( Точка )', link: 'https://go.2gis.com/k4d9F' },
  { name: 'Мастер 2 ( Master Coffee )', link: 'https://go.2gis.com/pscw1' },
  { name: 'Пятый угол ( Пятый угол )', link: 'https://go.2gis.com/0XUhe' },
  { name: 'Вкус (New Вкус)', link: 'https://go.2gis.com/XLAca' },
  { name: 'Атырау (Гурьев)', link: 'https://go.2gis.com/0gE7E' },
  { name: 'Огонек Момышулы (Огонек)', link: 'https://go.2gis.com/HpzfH' },
  { name: 'Огонек Балкантау (Огонек)', link: 'https://go.2gis.com/Z155A' },
  { name: 'Огонек Жумабаева (Огонек)', link: 'https://go.2gis.com/J6d4a' },
  { name: 'Огонек  Бараева (Огонек)', link: 'https://go.2gis.com/mAuME' },
  { name: 'Арабика ( Arabica City cafe )', link: 'https://go.2gis.com/qAeG1' },
  { name: 'Аура 2(Aura Verdant)', link: 'https://2gis.kz/astana/geo/9570759093518340/71.429471%2C51.108118?m=71.429882%2C51.107966%2F18.2' },
  { name: 'Юми суши (YouMe Sushi )', link: 'https://go.2gis.com/pSyn3' },
  { name: 'Креп Мангилик (CrepeCafe)', link: 'https://go.2gis.com/hM85y' },
  { name: 'Креп Кунаев (CrepeCafe)', link: 'https://go.2gis.com/Rc1L8' },
  { name: 'Креп Иманова (CrepeCafe)', link: 'https://go.2gis.com/PdBPQ' },
  { name: 'Ария (Ariya)', link: 'https://go.2gis.com/KR5cD' },
  { name: 'Чия (Chia)', link: 'https://go.2gis.com/E2brk' },
  { name: 'Мясоед (Мясоед)', link: 'https://go.2gis.com/YSsex' },
  { name: 'Тумар (Tumar)', link: 'https://go.2gis.com/CLvth' },
  { name: 'Хан (XAN)', link: 'https://go.2gis.com/xuAnm' },
  { name: 'Негрони (Negroni)', link: 'https://go.2gis.com/TXAns' },
  { name: 'GB (Golden Birds)', link: 'https://go.2gis.com/TXAns' },
  { name: 'Таш (Tash)', link: 'https://go.2gis.com/TXAns' },
  { name: 'Керей (Sushifox)', link: 'https://go.2gis.com/wxrVX' },
  { name: 'Аяла (Aiala Coffee+Wine)', link: 'https://go.2gis.com/SksXt' },
  { name: 'Креветка (Креветка)', link: 'https://go.2gis.com/MdCpN' },
  { name: 'Лепим мега (Лепим и варим )', link: 'https://go.2gis.com/nV9id' },
  { name: 'Набка (Coffee Boom)', link: 'https://go.2gis.com/mvXjM' },
  { name: 'Ол стирт (Wall Street Restaurant)', link: 'https://go.2gis.com/8uAF5' },
  { name: 'Италиата ( Italiata )', link: 'https://go.2gis.com/ZotTX' },
  { name: 'Огонек Аркайым ( Огонек )', link: 'https://go.2gis.com/0H467' },
  { name: 'Папа Мангилик (Papa John\'s)', link: 'https://go.2gis.com/lxWVU' },
  { name: 'Папа республика (Papa John\'s)', link: 'https://go.2gis.com/Rr91X' },
  { name: 'Папа Нурмагамбетова (Papa John\'s)', link: 'https://go.2gis.com/uQLHN' },
  { name: 'Папа Азия парк (Papa John\'s)', link: 'https://go.2gis.com/97bPD' },
  { name: 'Гулияни Абу даби (Guliani )', link: 'https://go.2gis.com/mP2Bk' },
  { name: 'Лепим Хан шатыр (Лепим и варим)', link: 'https://go.2gis.com/52xmj' },
  { name: 'лепим Керуен (Лепим и варим)', link: 'https://go.2gis.com/iAFr3' },
  { name: 'Шипа Палау (Shipa Palau)', link: 'https://go.2gis.com/NMwVw' },
  { name: 'Эспрессо Бар (Espresso Bar)', link: 'https://go.2gis.com/RIkLw' },
  { name: 'Алтын Палау (Altyn Palau)', link: 'https://go.2gis.com/F2Npr' },
  { name: 'Вин (Win Bar)  в 2 гисе нету', link: 'https://go.2gis.com/AEoTO' },
  { name: 'Карамель (Caramel)', link: 'https://go.2gis.com/jwiJz' },
  { name: 'Гранд ( Grand Festival)', link: 'https://go.2gis.com/ttxgt' },
  { name: 'Казбек (Казбек)', link: 'https://go.2gis.com/ivo7l' },
  { name: 'Креп сыганак ( CrepeCafe )', link: 'https://go.2gis.com/n25gp' },
  { name: 'БД Туран (Bodrum coffee )', link: 'https://go.2gis.com/cD7zV' },
  { name: 'БД Парксайд (Bodrum coffee )', link: 'https://go.2gis.com/uQOnM' },
  { name: 'БД Толеби (Bodrum coffee )', link: 'https://go.2gis.com/JSAMf' },
  { name: 'Баскет (Ocean Basket)', link: 'https://go.2gis.com/DeWm3' },
  { name: 'Кофе бум тауелсиздик (Coffee BOOM)', link: 'https://go.2gis.com/6S6yf' },
  { name: 'Траторрия ( TRATTORIA )', link: 'https://go.2gis.com/FX1j1' },
  { name: 'Сундук ( Sunduk)', link: 'https://go.2gis.com/ICKQ0' },
  { name: 'Пауланер (Paulaner)', link: 'https://go.2gis.com/DNfhP' },
  { name: 'Пражик (Пражечка)', link: 'https://go.2gis.com/HRt5a' },
  { name: 'цех руми (Руми цех)', link: 'https://go.2gis.com/69pse' },
  { name: 'Измир кунаева (Измир)', link: 'https://go.2gis.com/9m3z4' },
  { name: 'Дио (Dio Grand Cafe)', link: 'https://go.2gis.com/CVRdY' },
  { name: 'Пабло (Pablo)', link: 'https://go.2gis.com/AZ0ym' },
  { name: 'Том      ( Tom\'s )', link: 'https://go.2gis.com/9ndem' },
  { name: 'Пульс (Пульс кофейня )', link: 'https://go.2gis.com/XTEyV' },
  { name: 'Амора (Amore Pizza)', link: 'https://2gis.kz/astana/geo/70000001110459952' },
  { name: 'Рыба (Хочу Рыбу)', link: 'https://2gis.kz/astana/geo/70000001092837417' },
  { name: 'Пражечка ( пражечка гриль бар )', link: 'https://go.2gis.com/qesRg' },
  { name: 'Точка 2  (Точка bistro)', link: 'https://go.2gis.com/b909q' },
  { name: 'оншот Альфа (ONESHOTT COFFEE kitchen)', link: 'https://go.2gis.com/hALIK' },
  { name: 'Стейк (Steak&Brew)', link: 'https://go.2gis.com/YyfNr' },
  { name: 'Тагам туркестан (Тагам)', link: 'https://go.2gis.com/m5L1i' },
  { name: 'Гастерия Амман (Gasteria)', link: 'https://go.2gis.com/lx1Gu' },
  { name: 'Юнион (Оншот)', link: 'https://go.2gis.com/bLuEP' },
  { name: 'НУ (Onergy Kitchen)', link: 'https://go.2gis.com/d1gjT' },
  { name: 'Густо (La Gustosa)', link: 'https://go.2gis.com/1HVZU' },
  { name: 'Пулбир (Pool&beer )', link: 'https://go.2gis.com/4b8JJ' }
];
